### ISSUE TITLE
geGL context declaration missing GEGL_EXPORT macro

### ISSUE THREAD

**Issue by forry** [dormon/geGL#3]
Because of a bad habit of not giving the export macro infront of the whole class with public interface, you (probably) forgot to prefix all of the methods in generated/ContextDeclarations.h with the macro in question. The context methods are therefore unacessible on **windows** platform by default.
Tested this with couple of them and prefixing the macro made the unresolved external error disappear. 

Happy regenerating,
forry

**Comment by dormon** [comment]
Fixed
